<?php if (count($flash) > 0): ?>
    <ul>
        <?php foreach ($flash as $messages): ?>
            <?php foreach ($messages as $message): ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>


<a href="/posts/new">Новый пост</a>


<?php foreach ($posts as $post) : ?>
    <div>
        <a href="/posts/<?= $post['slug'] ?>"><?= htmlspecialchars($post['name']) ?></a>
    </div>
<?php endforeach ?>

<br>

<div>
    <a href="?page=<?= $page < 2 ? 1 : $page - 1 ?>">Prev</a> <a href="?page=<?= $page + 1 ?>">Next</a>
</div>