<?php if (count($flash) > 0): ?>
    <ul>
        <?php foreach ($flash as $messages): ?>
            <?php foreach ($messages as $message): ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>


<a href="/posts/new">Новый пост</a>

<pre>
    <?php
    // var_dump($posts);
    ?>
</pre>

<?php foreach ($posts as $post) : ?>
    <div>
        <a href="/posts/<?= $post['id'] ?>"><?= htmlspecialchars($post['name']) ?></a>
        <a href="/posts/<?= $post['id'] ?>/edit">изменить</a>

        <form action="/posts/<?= $post['id'] ?>" method="post" style="display: inline-block">
            <input type="hidden" name="_METHOD" value="DELETE">
            <input type="submit" value="Удалить">
        </form>

    </div>
    <hr>
<?php endforeach ?>

<br>

<div>
    <a href="?page=<?= $page < 2 ? 1 : $page - 1 ?>">Prev</a> <a href="?page=<?= $page + 1 ?>">Next</a>
</div>